Traceback (most recent call last):
  File "C:\Users\edier\miniconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\edier\miniconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edier\AppData\Roaming\Python\Python311\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\edier\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\edier\miniconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\edier\miniconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\edier\miniconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import zipfile, io
z = zipfile.ZipFile(io.BytesIO(r.content))
z.extractall("mundo")
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mBadZipFile[0m                                Traceback (most recent call last)
Cell [1;32mIn[3], line 2[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mzipfile[39;00m[38;5;241m,[39m [38;5;21;01mio[39;00m
[1;32m----> 2[0m z [38;5;241m=[39m [43mzipfile[49m[38;5;241;43m.[39;49m[43mZipFile[49m[43m([49m[43mio[49m[38;5;241;43m.[39;49m[43mBytesIO[49m[43m([49m[43mr[49m[38;5;241;43m.[39;49m[43mcontent[49m[43m)[49m[43m)[49m
[0;32m      3[0m z[38;5;241m.[39mextractall([38;5;124m"[39m[38;5;124mmundo[39m[38;5;124m"[39m)

File [1;32m~\miniconda3\Lib\zipfile.py:1302[0m, in [0;36mZipFile.__init__[1;34m(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps, metadata_encoding)[0m
[0;32m   1300[0m [38;5;28;01mtry[39;00m:
[0;32m   1301[0m     [38;5;28;01mif[39;00m mode [38;5;241m==[39m [38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m:
[1;32m-> 1302[0m         [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_RealGetContents[49m[43m([49m[43m)[49m
[0;32m   1303[0m     [38;5;28;01melif[39;00m mode [38;5;129;01min[39;00m ([38;5;124m'[39m[38;5;124mw[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mx[39m[38;5;124m'[39m):
[0;32m   1304[0m         [38;5;66;03m# set the modified flag so central directory gets written[39;00m
[0;32m   1305[0m         [38;5;66;03m# even if no files are added to the archive[39;00m
[0;32m   1306[0m         [38;5;28mself[39m[38;5;241m.[39m_didModify [38;5;241m=[39m [38;5;28;01mTrue[39;00m

File [1;32m~\miniconda3\Lib\zipfile.py:1369[0m, in [0;36mZipFile._RealGetContents[1;34m(self)[0m
[0;32m   1367[0m     [38;5;28;01mraise[39;00m BadZipFile([38;5;124m"[39m[38;5;124mFile is not a zip file[39m[38;5;124m"[39m)
[0;32m   1368[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m endrec:
[1;32m-> 1369[0m     [38;5;28;01mraise[39;00m BadZipFile([38;5;124m"[39m[38;5;124mFile is not a zip file[39m[38;5;124m"[39m)
[0;32m   1370[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mdebug [38;5;241m>[39m [38;5;241m1[39m:
[0;32m   1371[0m     [38;5;28mprint[39m(endrec)

[1;31mBadZipFile[0m: File is not a zip file

